{% set name = "boa" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/boa/archive/{{ version }}.tar.gz
  sha256: 6fa273a2ba180422e48dfda032dd3d544efc6fd7328e23f21bc015a53f311539

build:
  noarch: python
  number: 0
  script: $PYTHON -m pip install . --no-deps -vv
  entry_points:
    - conda-mambabuild = boa.cli.mambabuild:main
    - boa = boa.cli.boa:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - conda-build 3.20.*
    - pyyaml
    - colorama
    - ruamel.yaml
    - mamba 0.5.*
    - tabulate
    - jinja2
    - rich
    # for python 3.6 compatibility
    - dataclasses

test:
  imports:
    - boa
    - boa.cli
  commands:
    - boa -h

about:
  home: https://github.com/mamba-org/boa
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The mamba-powered conda package builder

extra:
  recipe-maintainers:
    - wolfv
