{% set name = "boa" %}
{% set version = "0.0.1.dev1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/TheSnakePit/boa/archive/{{ version }}.tar.gz
  sha256: 9ef31e4b6510745af45b1cf0f9d911c4ffac71e49a069cf1b3fe579e00e627ad

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - conda-mambabuild = boa.cli.mambabuild:main
    - boa = boa.cli.boa:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - conda-build >=3.19.2,<4
    - pyyaml
    - colorama
    - ruamel.yaml
    - mamba >=0.4.2
    - tabulate

test:
  imports:
    - boa
    - boa.cli
  commands:
    - boa -h

about:
  home: https://github.com/TheSnakePit/boa
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The mamba-powered conda package builder

extra:
  recipe-maintainers:
    - wolfv
