{% set name = "boa" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/boa/archive/{{ version }}.tar.gz
  sha256: 86fe7033ab2a7335284f62465587648ef037c7ac03111c01da464852e4631d36

build:
  noarch: python
  script: $PYTHON -m pip install . --no-deps -vv
  entry_points:
    - conda-mambabuild = boa.cli.mambabuild:main
    - boa = boa.cli.boa:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - conda-build 3.20.*
    - mamba >=0.6.4
    - ruamel.yaml
    - jinja2
    - rich
    - prompt_toolkit
    - json5
    - jsonschema
    - inotify_simple  # [unix]
    # for python 3.6 compatibility
    - dataclasses

test:
  imports:
    - boa
    - boa.cli
  commands:
    - boa -h

about:
  home: https://github.com/mamba-org/boa
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The mamba-powered conda package builder

extra:
  recipe-maintainers:
    - wolfv
