{% set name = "boa" %}
{% set version = "0.0.1.dev2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/TheSnakePit/boa/archive/{{ version }}.tar.gz
  sha256: 1e8cc53a999691353ba7e7dcb4b215713bab1d7f8079f5186d4fb81667863463

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - conda-mambabuild = boa.cli.mambabuild:main
    - boa = boa.cli.boa:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - conda-build >=3.19.2,<4
    - pyyaml
    - colorama
    - ruamel.yaml
    - mamba >=0.4.2
    - tabulate
    # for python 3.6 compatibility
    - dataclasses

test:
  imports:
    - boa
    - boa.cli
  commands:
    - boa -h

about:
  home: https://github.com/TheSnakePit/boa
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The mamba-powered conda package builder

extra:
  recipe-maintainers:
    - wolfv
