{% set name = "boa" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/boa/archive/{{ version }}.tar.gz
  sha256: 02f67fcd8ef1db3e399c82e9ded34039e741c6accfcebd089747e82fcb356979

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0
  entry_points:
    - conda-mambabuild = boa.cli.mambabuild:main
    - boa = boa.cli.boa:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - conda-build >=3.20,<3.22
    - mamba >=0.7
    - ruamel.yaml
    - jinja2
    - rich
    - prompt_toolkit
    - json5
    - jsonschema
    - joblib
    - inotify_simple  # [unix]
    # for python 3.6 compatibility
    - dataclasses

test:
  imports:
    - boa
    - boa.cli
  commands:
    - boa -h

about:
  home: https://github.com/mamba-org/boa
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The mamba-powered conda package builder

extra:
  recipe-maintainers:
    - wolfv
