{% set name = "boa" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/boa/archive/{{ version }}.tar.gz
  sha256: 1efebeff2733779b30c1a0bf61a07d63308f6474239286c7b3f0705ccf943ecf

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - conda-mambabuild = boa.cli.mambabuild:main
    - boa = boa.cli.boa:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - conda-build 3.20.*
    - mamba >=0.6.4
    - ruamel.yaml
    - jinja2
    - rich
    - prompt_toolkit
    - json5
    - jsonschema
    - joblib
    - inotify_simple  # [unix]
    # for python 3.6 compatibility
    - dataclasses

test:
  imports:
    - boa
    - boa.cli
  commands:
    - boa -h

about:
  home: https://github.com/mamba-org/boa
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The mamba-powered conda package builder

extra:
  recipe-maintainers:
    - wolfv
